name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        cd ../frontend
        npm ci
        
    - name: Build
      run: |
        cd backend
        npm run build --if-present
        cd ../frontend
        ng build --prod
        
    - name: Test
      run: |
        cd backend
        npm test
        cd ../frontend
        ng test --watch=false --browsers=ChromeHeadless

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          cd ~/greythr-crm &&
          git pull origin main &&
          cd backend &&
          npm install &&
          pm2 restart app &&
          cd ../frontend &&
          npm install &&
          ng build --prod &&
          sudo cp -r dist/* /var/www/html/
        '